### ISSUE TITLE
bug: webpack plugin not found

### ISSUE THREAD

**Issue by Rastraponovich** [secundant/neodx#104]
Hello, webpack configuration in manual not work 

upd: it's just a ts conflict.

import svg from '@neodx/svg/webpack';

<img width="951" alt="image" src="https://github.com/secundant/neodx/assets/58354560/ec12a91e-2bae-45e8-8ce7-00f81a07ca36">

**Comment by secundant** [comment]
@Rastraponovich Check a new 0.5.1 version, it was fixed under #114
